version: '3'

services:
  nginx:
    image: nginx:v1.0
    container_name: nginx
    ports:
      - "443:443"
    build:
      context: ./requirements/nginx
    volumes:
      - WordPress:/var/www/wordpress
    restart: on-failure
    networks:
      - Br1

  mariadb:
    image: mariadb:v1.0
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - DB:/var/lib/mysql/wordpress
    restart: on-failure
#    env_file:
#      - mariadb.env
    networks:
      - Br1

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:v1.0
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    expose:
      - "9000"
    env_file:
      - wp.env
    volumes:
      - WordPress:/var/www/wordpress
    restart: on-failure
    networks:
      - Br1

networks:
  Br1:
    driver: bridge

volumes:
    WordPress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/kyukim/data/WordPress'
    DB:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/kyukim/data/wp_DB'
  