version: '3'

services:
  nginx:
    image: nginx:v1.0
    ports:
      - "80:80"
    build:
      context: ./requirements/nginx
  mariadb:
    image: mariadb:v1.0
    build:
      context: ./requirements/mariadb
  wordpress:
    image: wordpress:v1.0
    build:
      context: ./requirements/wordpress